"""Drive organization, backup, and archive services."""

from __future__ import annotations

import shutil
import tarfile
import zipfile
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from sqlalchemy.orm import Session

from drive_intelligence_platform.core.config import AppSettings
from drive_intelligence_platform.models.entities import OperationManifest
from drive_intelligence_platform.schemas import RecommendationPayload, ScannedFile
from drive_intelligence_platform.services.classifier import ClassifierService
from drive_intelligence_platform.services.execution import ExecutionService, ExecutionPlan
from drive_intelligence_platform.services.scanner import DriveScanner


@dataclass(slots=True)
class OrganizationPlanEntry:
    """A single planned organization move."""

    source: Path
    destination: Path
    recommendation: RecommendationPayload


@dataclass(slots=True)
class BackupArtifact:
    """A backup or archive artifact generated by the app."""

    path: Path
    size_bytes: int
    method: str


class DriveManagementService:
    """Generate organization plans, backup archives, and execute approved moves."""

    def __init__(self, settings: AppSettings, session: Session | None = None) -> None:
        self.settings = settings
        self.session = session
        self.scanner = DriveScanner(max_workers=settings.max_workers, batch_size=settings.batch_size)
        self.classifier = ClassifierService(settings)

    def build_organization_plan(
        self,
        source_root: Path,
        destination_root: Path,
        progress_callback: Callable[[float, str], None] | None = None,
    ) -> list[OrganizationPlanEntry]:
        """Scan a source root and derive a move plan under a destination root."""

        def scan_progress(processed: int, total: int, current_path: Path | None) -> None:
            if progress_callback is None:
                return
            if total <= 0:
                progress_callback(0.0, "Scanning candidate files...")
                return
            ratio = 0.5 * (processed / total)
            label = f"Scanning {processed}/{total} files"
            if current_path is not None:
                label = f"{label} - {current_path}"
            progress_callback(ratio, label)

        scan_result = self.scanner.scan([source_root], progress_callback=scan_progress if progress_callback else None)
        plan: list[OrganizationPlanEntry] = []
        total_files = len(scan_result.files)
        for index, scanned_item in enumerate(scan_result.files, start=1):
            recommendation = self.classifier.classify(scanned_item)
            destination = destination_root / recommendation.suggested_folder / scanned_item.name
            plan.append(OrganizationPlanEntry(source=scanned_item.path, destination=destination, recommendation=recommendation))

            if progress_callback is not None:
                ratio = 0.5 + (0.5 * (index / total_files)) if total_files else 1.0
                progress_callback(ratio, f"Classifying {index}/{total_files} files - {scanned_item.path}")

        if progress_callback is not None:
            progress_callback(1.0, f"Built organization plan for {len(plan)} files")
        return plan

    def execute_organization_plan(self, plan: list[OrganizationPlanEntry], approved: bool) -> list[OperationManifest]:
        """Execute approved file moves and persist manifests."""

        if self.session is None:
            raise RuntimeError("A database session is required to execute an organization plan.")
        execution = ExecutionService(self.session)
        manifests: list[OperationManifest] = []
        for item in plan:
            operation = execution.execute_move(item.source, item.destination, approved=approved)
            manifests.append(operation)
        self.session.commit()
        return manifests

    def backup_folder(self, source_root: Path, output_root: Path, archive_name: str, method: str = "zip") -> BackupArtifact:
        """Create a backup archive or mirrored copy of a folder."""

        output_root.mkdir(parents=True, exist_ok=True)
        if method == "copy":
            destination = output_root / archive_name
            if destination.exists():
                shutil.rmtree(destination)
            shutil.copytree(source_root, destination)
            return BackupArtifact(path=destination, size_bytes=self._folder_size(destination), method="copy")

        if method == "tar.gz":
            destination = output_root / f"{archive_name}.tar.gz"
            with tarfile.open(destination, "w:gz") as tar_handle:
                tar_handle.add(source_root, arcname=source_root.name)
            return BackupArtifact(path=destination, size_bytes=destination.stat().st_size, method="tar.gz")

        destination = output_root / f"{archive_name}.zip"
        with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as zip_handle:
            for path in source_root.rglob("*"):
                if path.is_file():
                    zip_handle.write(path, arcname=path.relative_to(source_root.parent))
        return BackupArtifact(path=destination, size_bytes=destination.stat().st_size, method="zip")

    def create_archive(self, source_root: Path, output_root: Path, archive_name: str, method: str = "zip") -> BackupArtifact:
        """Alias for backup creation when the user wants to archive a folder."""

        return self.backup_folder(source_root=source_root, output_root=output_root, archive_name=archive_name, method=method)

    def planned_recommendations(self, source_root: Path, target_root: Path) -> list[tuple[ScannedFile, RecommendationPayload]]:
        """Return scan/classification pairs for UI previews."""

        scan_result = self.scanner.scan([source_root])
        preview: list[tuple[ScannedFile, RecommendationPayload]] = []
        for scanned_item in scan_result.files:
            recommendation = self.classifier.classify(scanned_item)
            preview.append((scanned_item, recommendation))
        return preview

    def _folder_size(self, root: Path) -> int:
        total = 0
        for path in root.rglob("*"):
            if path.is_file():
                total += path.stat().st_size
        return total
