"""Drive organization, backup, and archive services."""

from __future__ import annotations

import shutil
import tarfile
import zipfile
from collections import Counter, defaultdict
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import cast

from sqlalchemy.orm import Session

from drive_intelligence_platform.core.config import AppSettings
from drive_intelligence_platform.models.entities import OperationManifest
from drive_intelligence_platform.schemas import RecommendationPayload, ScannedFile
from drive_intelligence_platform.services.classifier import ClassifierService
from drive_intelligence_platform.services.execution import ExecutionService, ExecutionPlan
from drive_intelligence_platform.services.scanner import DriveScanner


@dataclass(slots=True)
class OrganizationPlanEntry:
    """A single planned organization move."""

    source: Path
    destination: Path
    recommendation: RecommendationPayload


@dataclass(slots=True)
class BackupArtifact:
    """A backup or archive artifact generated by the app."""

    path: Path
    size_bytes: int
    method: str


class DriveManagementService:
    """Generate organization plans, backup archives, and execute approved moves."""

    def __init__(self, settings: AppSettings, session: Session | None = None) -> None:
        self.settings = settings
        self.session = session
        self.scanner = DriveScanner(max_workers=settings.max_workers, batch_size=settings.batch_size)
        self.classifier = ClassifierService(settings)

    def build_organization_plan(
        self,
        source_root: Path,
        destination_root: Path,
        progress_callback: Callable[[float, str], None] | None = None,
        conservative_mode: bool = True,
        min_move_confidence: float = 0.90,
    ) -> list[OrganizationPlanEntry]:
        """Scan a source root and derive a move plan under a destination root."""

        def scan_progress(processed: int, total: int, current_path: Path | None) -> None:
            if progress_callback is None:
                return
            if total <= 0:
                progress_callback(0.0, "Scanning candidate files...")
                return
            ratio = 0.5 * (processed / total)
            label = f"Scanning {processed}/{total} files"
            if current_path is not None:
                label = f"{label} - {current_path}"
            progress_callback(ratio, label)

        try:
            scan_result = self.scanner.scan(
                [source_root],
                progress_callback=scan_progress if progress_callback else None,
                compute_hashes=False,
            )
        except TypeError:
            scan_result = self.scanner.scan([source_root], progress_callback=scan_progress if progress_callback else None)
        use_file_level_ai = len(scan_result.files) <= self.settings.max_file_level_ai_items
        plan: list[OrganizationPlanEntry] = []
        classified_items: list[tuple[ScannedFile, RecommendationPayload]] = []
        total_files = len(scan_result.files)
        for index, scanned_item in enumerate(scan_result.files, start=1):
            try:
                recommendation = self.classifier.classify(scanned_item, allow_ai=use_file_level_ai)
            except TypeError:
                recommendation = self.classifier.classify(scanned_item)
            classified_items.append((scanned_item, recommendation))

            if progress_callback is not None:
                ratio = 0.5 + (0.5 * (index / total_files)) if total_files else 1.0
                progress_callback(ratio, f"Classifying {index}/{total_files} files - {scanned_item.path}")

        grouped: dict[Path, list[tuple[ScannedFile, RecommendationPayload]]] = defaultdict(list)
        for scanned_item, recommendation in classified_items:
            grouped[scanned_item.folder_path].append((scanned_item, recommendation))

        for folder_path, items in grouped.items():
            folder_ai_plan = self._folder_group_ai_plan(items)
            strategy = self._select_folder_strategy(
                folder_path,
                items,
                folder_ai_plan=folder_ai_plan,
                conservative_mode=conservative_mode,
                min_move_confidence=min_move_confidence,
            )
            relative_parent = self._relative_folder(folder_path, source_root)

            for scanned_item, recommendation in items:
                if strategy == "preserve_folder":
                    destination = destination_root / relative_parent / scanned_item.name
                    enriched = self._recommend_with_reason(
                        recommendation,
                        suggested_folder=relative_parent,
                        reason_prefix="Preserved folder context",
                        min_confidence=0.85,
                    )
                elif strategy == "photo_album":
                    suggested = Path("Photos") / relative_parent
                    destination = destination_root / suggested / scanned_item.name
                    enriched = self._recommend_with_reason(
                        recommendation,
                        suggested_folder=suggested,
                        reason_prefix="Grouped as photo album",
                        min_confidence=0.88,
                    )
                else:
                    ai_suggested_folder = self._folder_ai_target(folder_ai_plan)
                    ai_reason = str(folder_ai_plan.get("reason", "Folder-level AI plan")) if folder_ai_plan else "Folder-level AI plan"
                    ai_confidence = float(folder_ai_plan.get("confidence", 0.0)) if folder_ai_plan else 0.0
                    if ai_suggested_folder is not None and ai_confidence >= min_move_confidence:
                        destination = destination_root / ai_suggested_folder / scanned_item.name
                        enriched = self._recommend_with_reason(
                            recommendation,
                            suggested_folder=ai_suggested_folder,
                            reason_prefix=f"Folder AI plan ({ai_reason})",
                            min_confidence=ai_confidence,
                        )
                    elif recommendation.confidence < min_move_confidence or str(recommendation.suggested_folder).lower().endswith("unsorted"):
                        destination = destination_root / relative_parent / scanned_item.name
                        enriched = self._recommend_with_reason(
                            recommendation,
                            suggested_folder=relative_parent,
                            reason_prefix="Preserved for low-confidence safety",
                            min_confidence=recommendation.confidence,
                        )
                    else:
                        destination = destination_root / recommendation.suggested_folder / scanned_item.name
                        enriched = recommendation

                plan.append(OrganizationPlanEntry(source=scanned_item.path, destination=destination, recommendation=enriched))

        if progress_callback is not None:
            progress_callback(1.0, f"Built organization plan for {len(plan)} files")
        return plan

    def _select_folder_strategy(
        self,
        folder_path: Path,
        items: list[tuple[ScannedFile, RecommendationPayload]],
        folder_ai_plan: dict[str, object] | None,
        conservative_mode: bool,
        min_move_confidence: float,
    ) -> str:
        """Choose a safe folder-level strategy to avoid random file scattering."""

        file_count = len(items)
        if file_count == 0:
            return "default"

        kinds = {scanned.file_kind for scanned, _ in items}
        extensions = {scanned.extension for scanned, _ in items}
        avg_confidence = sum(rec.confidence for _, rec in items) / file_count
        suggested_counter = Counter(str(rec.suggested_folder) for _, rec in items)
        dominant_ratio = suggested_counter.most_common(1)[0][1] / file_count
        photo_ratio = sum(1 for scanned, _ in items if scanned.file_kind == "photo") / file_count

        folder_name = folder_path.name.lower()
        semantic_folder_keywords = {
            "project",
            "client",
            "finance",
            "tax",
            "invoice",
            "contract",
            "research",
            "thesis",
            "family",
            "wedding",
            "trip",
        }

        if photo_ratio >= 0.8 and file_count >= 5:
            return "photo_album"

        # Preserve mixed-content folders so related files stay together.
        if len(kinds) >= 2 and file_count >= 3:
            return "preserve_folder"
        if len(extensions) >= 4 and file_count >= 4:
            return "preserve_folder"
        if avg_confidence < min_move_confidence:
            return "preserve_folder"
        if dominant_ratio < 0.6 and file_count >= 3:
            return "preserve_folder"
        if any(token in folder_name for token in semantic_folder_keywords) and file_count >= 2:
            return "preserve_folder"
        if conservative_mode and file_count >= 2 and avg_confidence < 0.92:
            return "preserve_folder"
        if folder_ai_plan is not None and bool(folder_ai_plan.get("preserve_folder", False)):
            return "preserve_folder"

        return "default"

    def _folder_group_ai_plan(
        self,
        items: list[tuple[ScannedFile, RecommendationPayload]],
    ) -> dict[str, object] | None:
        """Call AI once for a folder group to improve contextual planning."""

        ai_service = getattr(self.classifier, "ai_service", None)
        if ai_service is None or not hasattr(ai_service, "recommend_folder_group"):
            return None

        files = [scanned for scanned, _ in items]
        context = {
            "heuristic_summary": {
                "avg_confidence": sum(rec.confidence for _, rec in items) / len(items),
                "top_suggested": [str(rec.suggested_folder) for _, rec in items[:8]],
            }
        }
        try:
            planner = cast(object, ai_service)
            response = planner.recommend_folder_group(files, context)  # type: ignore[attr-defined]
            if isinstance(response, dict):
                return response
        except Exception:
            return None
        return None

    def _folder_ai_target(self, folder_ai_plan: dict[str, object] | None) -> Path | None:
        """Extract a safe folder target from folder-level AI plan."""

        if not folder_ai_plan:
            return None
        suggested = folder_ai_plan.get("suggested_folder")
        if not suggested:
            return None
        folder = Path(str(suggested))
        if str(folder).strip() == "":
            return None
        return folder

    def _relative_folder(self, folder_path: Path, source_root: Path) -> Path:
        """Return a stable relative folder under source root."""

        try:
            relative = folder_path.relative_to(source_root)
            return relative if str(relative) != "." else Path("Root")
        except ValueError:
            return Path(folder_path.name or "Root")

    def _recommend_with_reason(
        self,
        recommendation: RecommendationPayload,
        suggested_folder: Path,
        reason_prefix: str,
        min_confidence: float,
    ) -> RecommendationPayload:
        """Create a contextual recommendation while preserving original rationale."""

        return RecommendationPayload(
            source_path=recommendation.source_path,
            category=recommendation.category,
            subcategory=recommendation.subcategory,
            suggested_folder=suggested_folder,
            reason=f"{reason_prefix}: {recommendation.reason}",
            confidence=max(recommendation.confidence, min_confidence),
        )

    def execute_organization_plan(self, plan: list[OrganizationPlanEntry], approved: bool) -> list[OperationManifest]:
        """Execute approved file moves and persist manifests."""

        if self.session is None:
            raise RuntimeError("A database session is required to execute an organization plan.")
        execution = ExecutionService(self.session)
        manifests: list[OperationManifest] = []
        for item in plan:
            operation = execution.execute_move(item.source, item.destination, approved=approved)
            manifests.append(operation)
        self.session.commit()
        return manifests

    def backup_folder(self, source_root: Path, output_root: Path, archive_name: str, method: str = "zip") -> BackupArtifact:
        """Create a backup archive or mirrored copy of a folder."""

        output_root.mkdir(parents=True, exist_ok=True)
        if method == "copy":
            destination = output_root / archive_name
            if destination.exists():
                shutil.rmtree(destination)
            shutil.copytree(source_root, destination)
            return BackupArtifact(path=destination, size_bytes=self._folder_size(destination), method="copy")

        if method == "tar.gz":
            destination = output_root / f"{archive_name}.tar.gz"
            with tarfile.open(destination, "w:gz") as tar_handle:
                tar_handle.add(source_root, arcname=source_root.name)
            return BackupArtifact(path=destination, size_bytes=destination.stat().st_size, method="tar.gz")

        destination = output_root / f"{archive_name}.zip"
        with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as zip_handle:
            for path in source_root.rglob("*"):
                if path.is_file():
                    zip_handle.write(path, arcname=path.relative_to(source_root.parent))
        return BackupArtifact(path=destination, size_bytes=destination.stat().st_size, method="zip")

    def create_archive(self, source_root: Path, output_root: Path, archive_name: str, method: str = "zip") -> BackupArtifact:
        """Alias for backup creation when the user wants to archive a folder."""

        return self.backup_folder(source_root=source_root, output_root=output_root, archive_name=archive_name, method=method)

    def planned_recommendations(self, source_root: Path, target_root: Path) -> list[tuple[ScannedFile, RecommendationPayload]]:
        """Return scan/classification pairs for UI previews."""

        try:
            scan_result = self.scanner.scan([source_root], compute_hashes=False)
        except TypeError:
            scan_result = self.scanner.scan([source_root])
        preview: list[tuple[ScannedFile, RecommendationPayload]] = []
        for scanned_item in scan_result.files:
            recommendation = self.classifier.classify(scanned_item)
            preview.append((scanned_item, recommendation))
        return preview

    def _folder_size(self, root: Path) -> int:
        total = 0
        for path in root.rglob("*"):
            if path.is_file():
                total += path.stat().st_size
        return total
